### PR TITLE
Add mkt_tok marketing tokens

### PR DESCRIPTION
**Pull request by Seanstoppable**

### CODE REVIEW

**Comment by jparise** [comment]
Looks good. Thanks, @Seanstoppable!

**Comment by fmarier** [comment]
By the way, the `mkt_tok` parameter is actually require for unsubscribe links to work: https://github.com/brave/brave-browser/issues/9018#issuecomment-631830739

**Comment by jparise** [comment]
@fmarier I haven't seen any recent updates to the linked issue. Were you able to determine if removing this token merely makes the unsubscribe process less convenient (by not prefilling the email address) or if it prevents unsubscribing entirely?

**Comment by fmarier** [comment]
> Were you able to determine if removing this token merely makes the unsubscribe process less convenient (by not prefilling the email address) or if it prevents unsubscribing entirely?

No, I don't have enough visibility over the backend to be able to know for sure, though having to type an email address manually also makes for a bad user experience and so I'm planning to exempt these unsubscribe requests from the filter built into Brave.

**Pull request merged**
